1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
Delete the found duplicate file.


In [1]:
import os

import hashlib
import os
def hash_string(input):
    byte_input=input.encode()
    hash_object=hashlib.sha256(byte_input)
    return hash_object.hexdigest()

#path ="C:/Users/tarasingh/Desktop/Python training data/New folder_assignment/"
path=input("Enter path")
filelist = {}
print("The path of files which are removed are:-")
for root, dirs, files in os.walk(path):
    for file in files:
        #append the file name to the list
        x=os.path.join(root,file)
        l=open(x)
        a=l.read()
        l.close()
        a=hash_string(a)
        if a in filelist.keys():
            os.remove(x)
            print(x)
        else:
            filelist[a]=x

Enter pathC:/Users/tarasingh/Desktop/Python training data/New folder_assignment/
The path of files which are removed are:-
C:/Users/tarasingh/Desktop/Python training data/New folder_assignment/test\test2.txt
C:/Users/tarasingh/Desktop/Python training data/New folder_assignment/test\test3.txt
C:/Users/tarasingh/Desktop/Python training data/New folder_assignment/test\testfake2.txt
C:/Users/tarasingh/Desktop/Python training data/New folder_assignment/test - Copy\test.txt
C:/Users/tarasingh/Desktop/Python training data/New folder_assignment/test - Copy\test2.txt
C:/Users/tarasingh/Desktop/Python training data/New folder_assignment/test - Copy\test3.txt
C:/Users/tarasingh/Desktop/Python training data/New folder_assignment/test - Copy\testfake.txt
C:/Users/tarasingh/Desktop/Python training data/New folder_assignment/test - Copy\testfake2.txt


2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]


In [21]:
import random
import string
lc=string.ascii_lowercase
uc=string.ascii_uppercase
d=string.digits
l=[]
l.append(random.choice(uc))
for i in range(2):
    l.append(random.choice(lc))
for i in range(2):
    l.append(random.choice(d))
l.append(random.choice(string.punctuation))
p=''
while len(l)>0:
    c=random.choice(l)
    p+=c
    l.remove(c)
print(p)


I04(pq


3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [70]:
import numpy as np
import math
def isPrime(n):
    for i in range(2,(n//2)+1):
        if n%i==0:
            return False
    return True

l=[[2,3,4,66],
  [25,31,42,656],
  [222,43,47,646],
  [22,31,14,166]]
s=int(len(l))
arr=np.array(l).reshape(s,s)
print('Input:-')
print(arr)

for i in range(s):
    for j in range(s):
        xx=i*s+j
        x=arr[i][j]
        arr[i][j]=x*x*x if isPrime(xx) else x

print('Output:-')        
print(arr)

Input:-
[[  2   3   4  66]
 [ 25  31  42 656]
 [222  43  47 646]
 [ 22  31  14 166]]
Output:-
[[        8        27        64    287496]
 [       25     29791        42 282300416]
 [      222        43        47 269586136]
 [       22     29791        14       166]]


4.	Python program to get the sum of every cubed value and its previous integer. 

In [71]:
def isCube(n):
    if n**(1/3)==abs(n**(1/3)):
        return True
    return False
ans=0
for i in range(s):
    for j in range(s):
        ans+=arr[i][j] if isCube(arr[i][j]) else 0
print(ans)

552234310


5.	Given two arrays, find their intersection. Examples:

Input:  arr1[] = [1, 3, 4, 5, 7]
             arr2[] = [2, 3, 5, 6]


In [30]:
import numpy as np
arr1=np.array([1,3,4,5,7])
arr2=np.array([2,3,5,6])
print(np.intersect1d(arr1,arr2))

[3 5]


6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [37]:
arr=np.arange(7,(7*7*7)+1,7).reshape(7,7)
print(arr)
print(arr[6][6])

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]
343


7.	Checker Board Patten using Numpy:
[   1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1  ]


In [43]:
x = np.ones((7, 5))
x[1::2, ::2] = 0
x[::2, 1::2] = 0
print(x)

[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]


8.	Create a given Matrix:
[  A,     B,     C,       D
   E,      F,     G,       H
    I,      a,      K,       L
   M,    N,     o,       P
   Q,     R,      S,       T
   U,     0,     W,      O ]

Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values


In [3]:
import numpy as np
import string
l=[[ 'A','B', 'C', 'D'],
   ['E', 'F', 'G', 'H' ],
   ['I', 'a', 'K', 'L' ],
   ['M', 'N', 'o', 'P' ],
   ['Q', 'R', 'S', 'T' ],
   ['U', '0', 'W', 'O' ]]
print(l)
def isVowel(a):
    a=a.lower()
    if a in {'a','e','i','o','u'}:
        return True
    return False

for i in range(len(l)):
    for j in range(len(l[0])):
        l[i][j]=np.nan if isVowel(l[i][j]) else l[i][j]

count=0
for i in range(len(l)):
    count+=l[i].count(np.nan)
print(count)

[['A', 'B', 'C', 'D'], ['E', 'F', 'G', 'H'], ['I', 'a', 'K', 'L'], ['M', 'N', 'o', 'P'], ['Q', 'R', 'S', 'T'], ['U', '0', 'W', 'O']]
7


In [68]:
#Second Method
import numpy as np
l=[[ 'A','B', 'C', 'D'],
   ['E', 'F', 'G', 'H' ],
   ['I', 'a', 'K', 'L' ],
   ['M', 'N', 'o', 'P' ],
   ['Q', 'R', 'S', 'T' ],
   ['U', '0', 'W', 'O' ]]
print(l)
def isVowel(a):
    a=a.lower()
    if a in {'a','e','i','o','u'}:
        return True
    return False

count=0
for i in range(len(l)):
    for j in range(len(l[0])):
        if isVowel(l[i][j]) :
            l[i][j]=np.nan
            count+=1

print(l)

print(count)

[['A', 'B', 'C', 'D'], ['E', 'F', 'G', 'H'], ['I', 'a', 'K', 'L'], ['M', 'N', 'o', 'P'], ['Q', 'R', 'S', 'T'], ['U', '0', 'W', 'O']]
[[nan, 'B', 'C', 'D'], [nan, 'F', 'G', 'H'], [nan, nan, 'K', 'L'], ['M', 'N', nan, 'P'], ['Q', 'R', 'S', 'T'], [nan, '0', 'W', nan]]
7
