### 1. Create this dictionary:
**{0: 0, 1: 1, 2: 8, 3: 27, 4: 64}
 using a dictionary comprehension.**

In [3]:
d={}
for i in range(5):
    d[i]=i*i*i
d

{0: 0, 1: 1, 2: 8, 3: 27, 4: 64}

### 2. if the length of a word is even print "even!"

In [5]:
st = 'Print every word in this sentence that has an even number of letters'

l=st.split(' ')
for i in l:
    if len(i)%2==0:
        print(i)

word
in
this
sentence
that
an
even
number
of


### 3. Generate Password: 17 characters , minimum 1 Uppercase, 1 lowercase, 1 digits and 2 minimun special characters

In [7]:
import random
import string
lc=string.ascii_lowercase
uc=string.ascii_uppercase
d=string.digits
s=string.punctuation
a=s+d+uc+lc
l=[]
l.append(random.choice(uc))
l.append(random.choice(lc))
l.append(random.choice(d))
l.append(random.choice(s))
l.append(random.choice(s))
for i in range(13):
    l.append(random.choice(a))
p=""
while len(l)>0:
    x=random.choice(l)
    p+=x
    l.remove(x)
print(p)

rY+~|kWtiJo=Nm1)'G


### 4. you are given a list which is [6, 15, 5, 3, 5, 14, 3, 202, 34, 235, 555, 6]. You have to sort it such that the seventh element is greatest of all, second element is greater than last element and second last element is not greater than sum of 8 and sixth element

In [29]:
l=[6,15,5,3,5,14,4,202,34,235,555,6]
a=l.copy()
a.sort()
m=max(l)
i=l.index(m)
l[i]=l[6]
l[6]=m
s=min(l)
i=l.index(a[0])
l[i]=l[-1]
l[-1]=s
i=l.index(a[1])
l[i]=l[len(l)-2]
l[len(l)-2]=a[1]
print(l)

[6, 15, 5, 6, 5, 14, 555, 202, 34, 235, 4, 3]


### 5. Write a program that prints the integers from 1 to 100. But for multiples of three print "Fizz" instead of the number, and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz".

In [8]:
for i in range(1,101):
    if(i%3==0 and i%5==0):
        print("FizzBuzz")
    elif(i%3==0):
        print("Fizz")
    elif(i%5==0):
        print("Buzz")
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


### 6. Write a program that accepts a sentence and calculate the number of letters and digits. Suppose the following input is supplied to the program.

In [9]:
import string
l,d=0,0
w=input()
for i in range(len(w)):
    if w[i].isdigit():
        d+=1
    elif w[i].islower() or w[i].isupper():
        l+=1
print("No of digit ",d)
print("No of letters ",l)

agfsg!54
No of digit  2
No of letters  5


### 7. Exercise: Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j

[[0, 0, 0, 0, 0],
 [0, 1, 2, 3, 4],
 [0, 2, 4, 6, 8]
 ..............]]

In [11]:
import numpy as np
x,y=int(input()),int(input())
l=[]
for i in range(x):
    ll=[]
    for j in range(y):
        ll.append(i*j)
    l.append(ll)
arr=np.array(l)
print(arr)

5
5
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]


## 8. For this challenge,
Create a bank account class that has two attributes:

owner balance and two methods:

deposit withdraw As an added requirement, withdrawals may not exceed the available balance.

Instantiate your class, make several deposits and withdrawals, and test to make sure the account can't be overdrawn.

In [13]:
class Bank_account:
    def __init__(self,owner,amount):
        self.owner=owner
        self.amount=amount
    
    def deposit(self,a):
        self.amount+=a
        print("Total amount",self.amount)
    
    def withdrawals(self,a):
        if(a>self.amount):
            print('Withdrawals amount is high')
        else:
            self.amount-=a
            print('Transection Successfull')
            print("Total amount",self.amount)
            
            
#object
obj=Bank_account('Tarandeep',15000)
obj.deposit(10000)
obj.withdrawals(10000)
obj.withdrawals(210000)


Total amount 25000
Transection Successfull
Total amount 15000
Withdrawals amount is high
